### ISSUE TITLE
isNull, isUndefined, isNullOrUndefined增加type predicate

### ISSUE THREAD

**Issue by mrdulin** [wz2cool/ts-commons#11]
没有[type predicates](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates), TS将无法narrow类型为`null`, `undefined`, `null | undefined`。

问题示例：

```ts
const isNull = (v: any) => v === null;
const isUndefined = (v: any) => v === undefined;

const isNullOrUndefined = (v: any) => isNull(v) || isUndefined(v);

function testIsNullOrUndefined(data: { id: number | undefined } | null) {
  if (isNullOrUndefined(data) || !data.id) return; // error
  data.id // error
}

function testIsNull(data: { id: number } | null) {
  if (isNull(data)) return;
  data.id // error
}

function testIsUndefined(data: { id: number } | undefined) {
  if (isUndefined(data)) return;
  data.id //error
}
```

[TS playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAlhAcgVwDapgXhgCgG4BcMAhmAJ4CUWAfDHlptmGqgNwBQoksCAqmABMApgDM4YIQKy5CJclUy16jbMkGjxkjp3DR4SFgHkATv2FiJU7PiKlKNfSnT4qAH1f6zGyy+0i1wFBw4DBQQtAAkgboJl4WkjgCxFDERADe8AJEzAC2AEZCxjAeauaaUgC+xTDM6FRp7DDwIrgITqix6vECicnEbh4AhEkpAHRwAlTGQlDIxmCsMAD0SzCFxiDGjTAjxONSK2vGG1sV7Oz+YIHBYKHhUFHtvSnpmdnI+YUwVR61qPXbOAtHBtFjPfpTGZzBbbXb7ZardabdhnC4BIIhMKRCBxcrg14Td6fIo-GClbySAFNIGtHFdPG7CiQ2bzDhNOETBFI05AA)

解决：增加type predicate

```ts
const isNull = (v: any): v is null => v === null;
const isUndefined = (v: any): v is undefined => v === undefined;

const isNullOrUndefined = (v: any): v is null | undefined => isNull(v) || isUndefined(v);

function testIsNullOrUndefined(data: { id: number | undefined } | null) {
  if (isNullOrUndefined(data) || !data.id) return; // pass
  data.id // number
}

function testIsNull(data: { id: number } | null) {
  if (isNull(data)) return;
  data.id // number
}

function testIsUndefined(data: { id: number } | undefined) {
  if (isUndefined(data)) return;
  data.id // number
}
```

[TS playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAlhAcgVwDapgXhgCgG4BcMAhmAJ4CURe8EMYaGmAfDDZh-YwNwBQokWAgCqYACYBTAGZwwEsVlyES5Km1oxk46bPlZW7Tlsky5Yvv3DRaKdAHkATqJO6F2fEVKVqGhuhgAPprapnosNoz4FIFBIiGuURZSWsBQcOAwUBLQAJJIjI7OOmY4YsRQxEQA3vBiRAwAtgBGEg6BwS5mMAC+7X6o0VW8MPBSuAi2qIXxJWUV0QFBAIRzxAB0cGLRDhJQyA5gfCOrGwoA9Gdcza283by8yWCp6WCZ2VB5k6XllTA1m-VkNc2r0gv1BsNRuN8uhvvNtrt9odISdNrd7o9nhksrkIEVQmI4b9-nUri0Qe1jMV5BCRnAxjg4p15ESKAi9gcjjBUWJbkA)

以及

```ts
function isNumber(value: any): boolean {
  return typeof value === 'number';
}

function testIsNumber(value: string | number) {
  if (isNumber(value)) return;
  value // string | number
}

function isNumberV2(value: any): value is number {
  return typeof value === 'number';
}

function testIsNumberV2(value: string | number) {
  if (isNumberV2(value)) return;
  value // string
}
```

参考： https://github.com/alibaba/ice/blob/master/packages/shared/src/is.ts

**Comment by wz2cool** [comment]
thx , mr has been merged
